### PR TITLE
A functional CONSTRUCT query is now used to retrieve resources.

### LINKED ISSUE #41: CriteriaExecution methods do not retrieve instance data.
Execution methods for criteria objects do not retrieve any information but the URIs of the resources. `resources` and `first` methods seem to have this problem. I used the example code in the documentation on `tripod (0.10.9)`. I had the same issue on `0.10.8`.
   
    # $project_path/app/models/person.rb
    class Person
      include Tripod::Resource

      # these are the default rdf-type and graph for resources of this class
      rdf_type 'http://example.com/person'
      graph_uri 'http://example.com/people'

      field :name, 'http://example.com/name'
      field :knows, 'http://example.com/knows', :multivalued => true, :is_uri => true
      field :aliases, 'http://example.com/alias', :multivalued => true
      field :age, 'http://example.com/age', :datatype => RDF::XSD.integer
      field :important_dates, 'http://example.com/importantdates', :datatype => RDF::XSD.date, :multivalued => true
    end

Adding data using the example in the documentation:
    
    > uri = 'http://example.com/ric'
    "http://example.com/ric"
    > p = Person.new(uri)
    #<Person:0x000000058578e8 @uri=#<RDF::URI:0x2c2bbc0 URI:http://example.com/ric>, @repository=#<RDF::Repository:0x2c2bb84()>, @new_record=true, @graph_uri=#<RDF::URI:0x2c2b9cc URI:http://example.com/people>>
    > p.name = 'Ric'
    "Ric"
    > p.age = 31
    31
    > p.aliases = ['Rich', 'Richard']
    ["Rich", "Richard"]
    > p.important_dates = [Date.new(2011,1,1)]
    [Sat, 01 Jan 2011]
    > p.save!
    true

`find` method seems to work fine:

    > ric = Person.find('http://example.com/ric') #=> returns a single Person object.
    #<Person:0x00000005c5d5c8 @uri=#<RDF::URI:0x2e2eaa8 URI:http://example.com/ric>, @repository=#<RDF::Repository:0x2e3dcc4()>, @new_record=false, @graph_uri=#<RDF::URI:0x2e2e8f0 URI:http://example.com/people>>

    > ric.age
    31

    > ric.name
    "Ric"

    > ric.aliases
    ["Richard", "Rich"]

`resources` method does not retrieve the fields for the target instances.

    > people = Person.all.resources #=> returns all people as an array
    #<Tripod::ResourceCollection:0x00000005c37148 @resources=[#<Person:0x00000005c32378 @uri=#<RDF::URI:0x2e19068 URI:http://example.com/ric>, @repository=#<RDF::Repository:0x2e1bda4()>, @new_record=false, @graph_uri=#<RDF::URI:0x2e18d48 URI:http://example.com/people>>], @criteria=#<Tripod::Criteria:0x000000059bc788 @resource_class=Person, @where_clauses=["?uri a <http://example.com/person>", "?uri ?p ?o"], @extra_clauses=[], @graph_uri="http://example.com/people">, @sparql_query_str=nil, @resource_class=nil, @return_graph=true>

    > people.count
    1

    > person = people.first
    #<Person:0x00000005c32378 @uri=#<RDF::URI:0x2e19068 URI:http://example.com/ric>, @repository=#<RDF::Repository:0x2e1bda4()>, @new_record=false, @graph_uri=#<RDF::URI:0x2e18d48 URI:http://example.com/people>>
    > person.uri
    #<RDF::URI:0x2e19068 URI:http://example.com/ric>
    > person.age
    nil
    > person.name
    nil
    > person.aliases
    []

Here is the Fuseki logs for the `resources` call.

    21:31:18 INFO  [110] POST http://127.0.0.1:3030/read_write_service/sparql
    21:31:18 INFO  [110] Query = SELECT DISTINCT ?uri (<http://example.com/people> as ?graph) WHERE { GRAPH <http://example.com/people> { ?uri a <http://example.com/person> . ?uri ?p ?o } }
    21:31:18 INFO  [110] exec/select
    21:31:18 INFO  [110] 200 OK (9 ms) 
    21:31:18 INFO  [111] POST http://127.0.0.1:3030/read_write_service/sparql
    21:31:18 INFO  [111] Query =          CONSTRUCT {           ?tripod_construct_s ?tripod_construct_p ?tripod_construct_o .                    }         WHERE {           { SELECT (?uri as ?tripod_construct_s) {             SELECT DISTINCT ?uri (<http://example.com/people> as ?graph) WHERE { GRAPH <http://example.com/people> { ?uri a <http://example.com/person> . ?uri ?p ?o } }           } }           ?tripod_construct_s ?tripod_construct_p ?tripod_construct_o .                    }       
    21:31:18 INFO  [111] exec/construct
    21:31:18 INFO  [111] 200 OK (8 ms) 

`first` yields the same issue.

    > person2 = Person.first
    #<Person:0x00000005d25dc0 @uri=#<RDF::URI:0x2e92ea4 URI:http://example.com/ric>, @repository=#<RDF::Repository:0x2e92120()>, @new_record=false, @graph_uri=#<RDF::URI:0x2e92c74 URI:http://example.com/people>>
    > person2.uri
    #<RDF::URI:0x2e92ea4 URI:http://example.com/ric>
    > person2.age
    nil
    > person2.name
    nil
    > person2.aliases
    []

The logs for `find` call.

    21:35:53 INFO  [112] POST http://127.0.0.1:3030/read_write_service/sparql
    21:35:53 INFO  [112] Query = SELECT * { SELECT DISTINCT ?uri (<http://example.com/people> as ?graph) WHERE { GRAPH <http://example.com/people> { ?uri a <http://example.com/person> . ?uri ?p ?o } } } LIMIT 1
    21:35:53 INFO  [112] exec/select
    21:35:53 INFO  [112] 200 OK (9 ms) 
    21:35:53 INFO  [113] POST http://127.0.0.1:3030/read_write_service/sparql
    21:35:53 INFO  [113] Query =          CONSTRUCT {           ?tripod_construct_s ?tripod_construct_p ?tripod_construct_o .                    }         WHERE {           { SELECT (?uri as ?tripod_construct_s) {             SELECT * { SELECT DISTINCT ?uri (<http://example.com/people> as ?graph) WHERE { GRAPH <http://example.com/people> { ?uri a <http://example.com/person> . ?uri ?p ?o } } } LIMIT 1           } }           ?tripod_construct_s ?tripod_construct_p ?tripod_construct_o .                    }       
    21:35:53 INFO  [113] exec/construct
    21:35:53 INFO  [113] 200 OK (10 ms) 

`CONSTRUCT` queries that hit the database do not seem to make sense, and they return empty graphs as one would expect.

### PR DESCRIPTION
**Pull request by muratseyhan**
I changed the mechanism to create functional `CONSTRUCT` queries to be used to retrieve resources. In the new mechanism, URI and graph pairs retrieved by the `_select_uris_and_graphs` method are being used to build up the `CONSTRUCT` query. The query is then used to retrieve the objects.

`resources` and `first` methods should be working as expected now. This change also allows us to retrieve data from multiple graphs with `find_by_spaqrl` (see the added test titled "extracts resources from specified graph".).
The following tests, which were failing, now pass:

    ./spec/tripod/embeds_spec.rb:44 # Tripod::Embeds given a saved instance retrieved as part of a resource collection should hydrate embedded resources from the triple store
    ./spec/tripod/finders_spec.rb:205 # Tripod::Finders.find_by_sparql returns an array of resources which match those in the db

This fixes #41  .

**Additional Explanation:**

I haven't removed the method `_describe_query_for_select`, which is creating a nonfunctional `CONSTRUCT` query. It is mainly because this required me to touch some parts that were not directly related with the issue that I wanted to address (issue #41), and I wanted to keep the changes easy to track in my first pull request.

### CODE REVIEW

**Comment by RicSwirrl** [comment]
Thanks for this. I'm really busy at the moment, but I'll review it when I get the chance.

**Comment by muratseyhan** [comment]
Thanks @RicSwirrl , that would be appreciated.

**Comment by RicSwirrl** [comment]
Hi @muratseyhan. This is nearly what we need. We're working on a minor tweak to this, and then we'll probably merge it. 

We're not really set up for external contributors at the mo, so before we merge it could you just confirm (as a response on this PR is fine) that you're agreeing to provide your code under the MIT licence and that you're granting Swirrl copyright on the code. We use Tripod in commerical products and we don't want to pollute the MIT license of this project by accident!

**Comment by muratseyhan** [comment]
I hereby confirm that I consent the use of my previous and future contributions to Tripod under the MIT licence and that I am granting Swirrl copyright for my contributions.

**Comment by muratseyhan** [comment]
Hi @RicSwirrl! Thanks for the prompt response. Let me know if the wording of the statement above is not OK. If so, I can copy-paste a statement that you provide. 

Your comment makes me wonder if you guys are cool with external people contributing to the project at the moment. I know it could sometimes be a burden to review contributions when you need to focus on other duties. I am building up a prototype for my MSc. studies heavily dependent on Tripod, and am willing to contribute further in the process.

**Pull request merged**
