### PR TITLE
Changed finders.rb to not use (?uri ?graph) VALUES claues, due to incompatibility with query rewriting.

### PR DESCRIPTION
**Pull request by RicSwirrl**

### CODE REVIEW

**Comment by asacalow** [comment]
Don't think this is for general release, I suggest that we set up a separate drafter branch for this..

**Comment by RicSwirrl** [comment]
Yeah - that's what this branch ls :)

**Comment by asacalow** [comment]
It should just be a branch rather than a pull request then I think – suggest branching a 'drafter' branch off master then merging this request over there :tropical_drink:

**Comment by RicSwirrl** [comment]
ok - happy to close this PR then.

**Pull request closed without merging**
